### ISSUE TITLE
fail to install

### ISSUE THREAD

**Issue by AdrienLemaire** [progandy/wdomirror#3]
Hi,

I found this plugin [here](https://github.com/swaywm/sway/wiki/Useful-add-ons-for-sway#remoterecording), and am hoping that this can serve as a  good alternative while https://github.com/swaywm/sway/issues/1666 is pending (allowing me to mirror my screen to an external monitor).

Your readme gives the following command, which fails for me
```console
$ meson build ninja -C build
usage: meson [-h] {setup,configure,dist,install,introspect,init,test,wrap,subprojects,help,rewrite,compile} ...
meson: error: unrecognized arguments: -C build
$ meson --version
0.57.0
```
Using arch linux and sway version 1.5-35342d89 (Feb 17 2021, branch 'master')

Can you explain the correct steps to install this plugin ? Thanks in advance!

**Comment by Sukid** [comment]
Just put in meson build first, then ninja -c build

Or meson build && ninja -C build

**Comment by AdrienLemaire** [comment]
@Sukid seems to work! Not what I expected, but it does the trick, lovely! Thanks for making this tool !
